service: hydroponics

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: master
  region: eu-central-1

functions:
  hello:
    handler: handler.handler